#!/usr/bin/env python
"""
Manage script for the Afrikasia coop backend.

This script is the entry point for administrative commands such as running
the development server, applying database migrations and creating
superusers. It is the standard ``manage.py`` generated by Django with a
custom project name.

Usage:
    python manage.py runserver
    python manage.py migrate
    python manage.py createsuperuser

The Django settings module is configured to use the project settings in
``afrikoop/settings.py``. See that file for more details about the
configuration.

Note: This file does not execute any logic on import. It simply sets up
the environment and delegates to Django's command line utility.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'afrikoop.settings')
    try:
        from django.core.management import execute_from_command_line  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available on "
            "your PYTHONPATH environment variable? Did you forget to activate a "
            "virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()